### ISSUE TITLE
Broken With Update in Udemy

### ISSUE THREAD

**Issue by theakhandpatel** [augustkimo/Udemy-Custom-Speed-Changer#2]
Hi,
The Extension doesn't seem to work with Udemy as of now. Kindly take a look.

**Comment by augustmuir** [comment]
Thanks for letting me know, will look at this tonight.

**Comment by augustmuir** [comment]
@akhand3108 it's still working perfectly for me. Try CTRL+Shift+R for a hard refresh from the video player page - it only supports the desktop web player. If you have more details for me to recreate feel free to open another issue, thanks!
