### ISSUE TITLE
Doesn't work on PC

### ISSUE THREAD

**Issue by lior-ashkenazi** [augustkimo/Udemy-Custom-Speed-Changer#4]
Chrome version: 115.0.5790.170 (Official Build) (64-bit) (cohort: 115_170 Stable Control(A)) 
![image](https://github.com/augustmuir/Udemy-Custom-Speed-Changer/assets/72506071/ee2d94d8-1a0a-4057-bc58-968641efc04a)

That's after deleting the browser's cache.

**Comment by sebmenard** [comment]
I confirm that it does not work anymore (using it on Microsoft Edge) since this summer.

**Comment by augustmuir** [comment]
Fixed #5 

Will upload to chrome web store now, but it takes a few days to be reviewed. You can load unpacked in the meantime.

Thanks for reporting, appreciate it!
